import { ReactNode } from 'react'
import type { Metadata } from 'next'
import NextLink from 'next/link'
import { Space_Grotesk } from 'next/font/google'

import { Providers } from './providers'
import CartIcon from '@/components/CartIcon'
import { Flex, Heading } from '@chakra-ui/react'

const font = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" className={font.className}>
      <body>
        <Providers>
          <Flex
            as="header"
            justify="space-between"
            align="center"
            p={4}
            bg="white"
            borderBottom="2px solid black"
            h={20}
          >
            <NextLink href="/">
              <Heading as="h1">Carbon Project Marketplace</Heading>
            </NextLink>
            <CartIcon />
          </Flex>
          {children}
        </Providers>
      </body>
    </html>
  )
}
